name: CommandBlocker
version: ${project.version}
main: dev.nxms.commandblocker.CommandBlocker
api-version: "1.21"
author: nxmsdev
website: https://www.nxms.dev
description: A plugin for blocking commands

depend:
  - packetevents

commands:
  commandblocker:
    description: Main command for CommandBlocker plugin
    usage: /<command> <add|remove|list|reload|help>
    aliases:
      - cb

permissions:
  commandblocker.command:
    description: Access to /commandblocker command
    default: op
  commandblocker.admin:
    description: Full access to all CommandBlock commands
    default: op
    children:
      commandblocker.command: true
      commandblocker.add: true
      commandblocker.remove: true
      commandblocker.list: true
      commandblocker.reload: true
      commandblocker.bypass: true
  commandblocker.add:
    description: Access to /commandblocker add
    default: op
  commandblocker.remove:
    description: Access to /commandblocker remove
    default: op
  commandblocker.list:
    description: Access to /commandblocker list
    default: op
  commandblocker.reload:
    description: Access to /commandblocker reload
    default: op
  commandblocker.bypass:
    description: Bypass blocked commands
    default: op